import type { ModelPrice } from './types'

// Fallback model prices when API is unavailable
// Prices are per 1M tokens
export const fallbackModelPrices: ModelPrice[] = [
  // OpenAI Models - Latest (March 2026)
  {
    provider: 'OpenAI',
    model: 'gpt-5.4',
    displayName: 'GPT-5.4',
    inputPricePer1M: 2.5,
    outputPricePer1M: 15.0,
    contextWindow: 272000,
    maxOutputTokens: 32000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
    description: 'Latest flagship model with enhanced reasoning and multimodal capabilities',
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5.4-pro',
    displayName: 'GPT-5.4 Pro',
    inputPricePer1M: 30.0,
    outputPricePer1M: 180.0,
    contextWindow: 272000,
    maxOutputTokens: 64000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
    description: 'Most capable model for complex tasks requiring deep analysis',
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5.2',
    displayName: 'GPT-5.2',
    inputPricePer1M: 1.75,
    outputPricePer1M: 14.0,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5.1',
    displayName: 'GPT-5.1',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.0,
    contextWindow: 200000,
    maxOutputTokens: 16000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5',
    displayName: 'GPT-5',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.0,
    contextWindow: 200000,
    maxOutputTokens: 16000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5-mini',
    displayName: 'GPT-5 Mini',
    inputPricePer1M: 0.25,
    outputPricePer1M: 2.0,
    contextWindow: 128000,
    maxOutputTokens: 16000,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Best balance of cost and capability for most use cases',
  },
  {
    provider: 'OpenAI',
    model: 'gpt-5-nano',
    displayName: 'GPT-5 Nano',
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 8000,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Ultra-low cost for simple tasks',
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4.1',
    displayName: 'GPT-4.1',
    inputPricePer1M: 2.0,
    outputPricePer1M: 8.0,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Million token context for long documents',
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 Mini',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    contextWindow: 1000000,
    maxOutputTokens: 16000,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4.1-nano',
    displayName: 'GPT-4.1 Nano',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1000000,
    maxOutputTokens: 8000,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4o',
    displayName: 'GPT-4o',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    contextWindow: 128000,
    maxOutputTokens: 16000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 16000,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  // OpenAI Reasoning Models
  {
    provider: 'OpenAI',
    model: 'o4-mini',
    displayName: 'o4-mini',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    isReasoning: true,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Fast reasoning model for complex tasks',
  },
  {
    provider: 'OpenAI',
    model: 'o3',
    displayName: 'o3',
    inputPricePer1M: 10.0,
    outputPricePer1M: 40.0,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    isReasoning: true,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Advanced reasoning with chain-of-thought',
  },
  {
    provider: 'OpenAI',
    model: 'o3-mini',
    displayName: 'o3-mini',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 200000,
    maxOutputTokens: 65536,
    isReasoning: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'o3-pro',
    displayName: 'o3 Pro',
    inputPricePer1M: 20.0,
    outputPricePer1M: 80.0,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    isReasoning: true,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'o1',
    displayName: 'o1',
    inputPricePer1M: 15.0,
    outputPricePer1M: 60.0,
    contextWindow: 200000,
    maxOutputTokens: 100000,
    isReasoning: true,
    supportsFunctionCalling: true,
    supportsJSON: true,
  },
  {
    provider: 'OpenAI',
    model: 'o1-mini',
    displayName: 'o1-mini',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    contextWindow: 128000,
    maxOutputTokens: 65536,
    isReasoning: true,
    supportsFunctionCalling: true,
    supportsJSON: true,
  },
  
  // Anthropic Models
  {
    provider: 'Anthropic',
    model: 'claude-4.6-opus',
    displayName: 'Claude 4.6 Opus',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
    description: 'Most capable Claude model for complex tasks',
  },
  {
    provider: 'Anthropic',
    model: 'claude-4.6-sonnet',
    displayName: 'Claude 4.6 Sonnet',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    contextWindow: 200000,
    maxOutputTokens: 16000,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-4-opus',
    displayName: 'Claude 4 Opus',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    contextWindow: 200000,
    maxOutputTokens: 32000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-4-sonnet',
    displayName: 'Claude 4 Sonnet',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    contextWindow: 200000,
    maxOutputTokens: 16000,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-3.5-sonnet',
    displayName: 'Claude 3.5 Sonnet',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-3.5-haiku',
    displayName: 'Claude 3.5 Haiku',
    inputPricePer1M: 0.8,
    outputPricePer1M: 4.0,
    contextWindow: 200000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Fast and affordable for high-volume tasks',
  },
  {
    provider: 'Anthropic',
    model: 'claude-3-opus',
    displayName: 'Claude 3 Opus',
    inputPricePer1M: 15.0,
    outputPricePer1M: 75.0,
    contextWindow: 200000,
    maxOutputTokens: 4096,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  
  // Google Models
  {
    provider: 'Google',
    model: 'gemini-3.1-pro',
    displayName: 'Gemini 3.1 Pro',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.0,
    contextWindow: 2000000,
    maxOutputTokens: 65536,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
    description: '2M context window for massive documents',
  },
  {
    provider: 'Google',
    model: 'gemini-3.1-flash',
    displayName: 'Gemini 3.1 Flash',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Ultra-fast with million token context',
  },
  {
    provider: 'Google',
    model: 'gemini-3-pro',
    displayName: 'Gemini 3 Pro',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.0,
    contextWindow: 2000000,
    maxOutputTokens: 65536,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
  },
  {
    provider: 'Google',
    model: 'gemini-3-flash',
    displayName: 'Gemini 3 Flash',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Google',
    model: 'gemini-2.5-pro',
    displayName: 'Gemini 2.5 Pro',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.0,
    contextWindow: 2000000,
    maxOutputTokens: 8192,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    isMultimodal: true,
    isReasoning: true,
    description: 'Advanced reasoning with massive context',
  },
  {
    provider: 'Google',
    model: 'gemini-2.5-flash',
    displayName: 'Gemini 2.5 Flash',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.3,
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Google',
    model: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  
  // Mistral Models
  {
    provider: 'Mistral',
    model: 'mistral-large',
    displayName: 'Mistral Large',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Top-tier Mistral model for complex tasks',
  },
  {
    provider: 'Mistral',
    model: 'mistral-small',
    displayName: 'Mistral Small',
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Mistral',
    model: 'codestral',
    displayName: 'Codestral',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    isCoding: true,
    supportsStreaming: true,
    description: 'Specialized for code generation and completion',
  },
  {
    provider: 'Mistral',
    model: 'pixtral-large',
    displayName: 'Pixtral Large',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsVision: true,
    isMultimodal: true,
    supportsStreaming: true,
    description: 'Multimodal model for vision tasks',
  },
  {
    provider: 'Mistral',
    model: 'ministral-8b',
    displayName: 'Ministral 8B',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.1,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
  },
  {
    provider: 'Mistral',
    model: 'ministral-3b',
    displayName: 'Ministral 3B',
    inputPricePer1M: 0.04,
    outputPricePer1M: 0.04,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
  },
  
  // AWS Bedrock Nova
  {
    provider: 'AWS Bedrock',
    model: 'nova-pro',
    displayName: 'Nova Pro',
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
    contextWindow: 300000,
    maxOutputTokens: 5000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    isMultimodal: true,
    description: 'AWS flagship multimodal model',
  },
  {
    provider: 'AWS Bedrock',
    model: 'nova-lite',
    displayName: 'Nova Lite',
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    contextWindow: 300000,
    maxOutputTokens: 5000,
    isPopular: true,
    supportsVision: true,
    supportsStreaming: true,
    isMultimodal: true,
  },
  {
    provider: 'AWS Bedrock',
    model: 'nova-micro',
    displayName: 'Nova Micro',
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.14,
    contextWindow: 128000,
    maxOutputTokens: 5000,
    supportsStreaming: true,
  },
  {
    provider: 'AWS Bedrock',
    model: 'nova-2-lite',
    displayName: 'Nova 2 Lite',
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
    supportsVision: true,
    supportsStreaming: true,
    isMultimodal: true,
  },
  {
    provider: 'AWS Bedrock',
    model: 'nova-2-pro',
    displayName: 'Nova 2 Pro',
    inputPricePer1M: 2.19,
    outputPricePer1M: 17.5,
    contextWindow: 1000000,
    maxOutputTokens: 32000,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    isMultimodal: true,
  },
  
  // DeepSeek
  {
    provider: 'DeepSeek',
    model: 'deepseek-v3',
    displayName: 'DeepSeek V3',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.1,
    contextWindow: 64000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Cost-effective with strong performance',
  },
  {
    provider: 'DeepSeek',
    model: 'deepseek-r1',
    displayName: 'DeepSeek R1',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    contextWindow: 64000,
    maxOutputTokens: 8192,
    isReasoning: true,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Advanced reasoning at low cost',
  },
  {
    provider: 'DeepSeek',
    model: 'deepseek-coder-v2',
    displayName: 'DeepSeek Coder V2',
    inputPricePer1M: 0.14,
    outputPricePer1M: 0.28,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isCoding: true,
    supportsStreaming: true,
    description: 'Specialized for code tasks',
  },
  
  // Qwen
  {
    provider: 'Qwen',
    model: 'qwq-32b',
    displayName: 'QwQ 32B',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 32000,
    maxOutputTokens: 16384,
    isReasoning: true,
    supportsStreaming: true,
    description: 'Reasoning-focused Qwen model',
  },
  {
    provider: 'Qwen',
    model: 'qwen-2.5-72b',
    displayName: 'Qwen 2.5 72B',
    inputPricePer1M: 0.35,
    outputPricePer1M: 0.4,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Qwen',
    model: 'qwen-2.5-32b',
    displayName: 'Qwen 2.5 32B',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Qwen',
    model: 'qwen-2.5-coder-32b',
    displayName: 'Qwen 2.5 Coder 32B',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.2,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isCoding: true,
    supportsStreaming: true,
    description: 'Optimized for code generation',
  },
  {
    provider: 'Qwen',
    model: 'qwen-vl-max',
    displayName: 'Qwen VL Max',
    inputPricePer1M: 2.0,
    outputPricePer1M: 4.0,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    supportsVision: true,
    isMultimodal: true,
    supportsStreaming: true,
    description: 'Vision-language multimodal model',
  },
  
  // Meta Llama
  {
    provider: 'Meta',
    model: 'llama-4-maverick',
    displayName: 'Llama 4 Maverick',
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextWindow: 1000000,
    maxOutputTokens: 65536,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Million token context with strong capabilities',
  },
  {
    provider: 'Meta',
    model: 'llama-4-scout',
    displayName: 'Llama 4 Scout',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.3,
    contextWindow: 1000000,
    maxOutputTokens: 32768,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  {
    provider: 'Meta',
    model: 'llama-3.3-70b',
    displayName: 'Llama 3.3 70B',
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  
  // Groq (fast inference)
  {
    provider: 'Groq',
    model: 'llama-3.3-70b-versatile',
    displayName: 'Llama 3.3 70B (Groq)',
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Ultra-fast inference via Groq',
  },
  {
    provider: 'Groq',
    model: 'llama-3.1-8b-instant',
    displayName: 'Llama 3.1 8B (Groq)',
    inputPricePer1M: 0.05,
    outputPricePer1M: 0.08,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Fastest inference for simple tasks',
  },
  {
    provider: 'Groq',
    model: 'mixtral-8x7b',
    displayName: 'Mixtral 8x7B (Groq)',
    inputPricePer1M: 0.24,
    outputPricePer1M: 0.24,
    contextWindow: 32000,
    maxOutputTokens: 8192,
    supportsStreaming: true,
    supportsJSON: true,
  },
  
  // xAI
  {
    provider: 'xAI',
    model: 'grok-2',
    displayName: 'Grok 2',
    inputPricePer1M: 5.0,
    outputPricePer1M: 15.0,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isFlagship: true,
    supportsVision: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Real-time knowledge via X integration',
  },
  {
    provider: 'xAI',
    model: 'grok-2-mini',
    displayName: 'Grok 2 Mini',
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextWindow: 128000,
    maxOutputTokens: 8192,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
  
  // Cohere
  {
    provider: 'Cohere',
    model: 'command-r-plus',
    displayName: 'Command R+',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    isFlagship: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
    description: 'Enterprise-grade with RAG capabilities',
  },
  {
    provider: 'Cohere',
    model: 'command-r',
    displayName: 'Command R',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextWindow: 128000,
    maxOutputTokens: 4096,
    isPopular: true,
    supportsFunctionCalling: true,
    supportsStreaming: true,
    supportsJSON: true,
  },
]

export const providers = [...new Set(fallbackModelPrices.map(m => m.provider))].sort()
