import type { ModelPrice } from './types'

export const modelPrices: ModelPrice[] = [
  // OpenAI Models
  {
    provider: 'OpenAI',
    model: 'gpt-4o',
    displayName: 'GPT-4o',
    inputPricePer1k: 0.005,
    outputPricePer1k: 0.015,
    contextWindow: 128000,
    isFlagship: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    inputPricePer1k: 0.00015,
    outputPricePer1k: 0.0006,
    contextWindow: 128000,
    isPopular: true,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-4-turbo',
    displayName: 'GPT-4 Turbo',
    inputPricePer1k: 0.01,
    outputPricePer1k: 0.03,
    contextWindow: 128000,
  },
  {
    provider: 'OpenAI',
    model: 'gpt-3.5-turbo',
    displayName: 'GPT-3.5 Turbo',
    inputPricePer1k: 0.0005,
    outputPricePer1k: 0.0015,
    contextWindow: 16385,
  },
  {
    provider: 'OpenAI',
    model: 'o1',
    displayName: 'o1',
    inputPricePer1k: 0.015,
    outputPricePer1k: 0.06,
    contextWindow: 200000,
    isFlagship: true,
  },
  {
    provider: 'OpenAI',
    model: 'o1-mini',
    displayName: 'o1 Mini',
    inputPricePer1k: 0.003,
    outputPricePer1k: 0.012,
    contextWindow: 128000,
  },
  // Google Models
  {
    provider: 'Google',
    model: 'gemini-1.5-pro',
    displayName: 'Gemini 1.5 Pro',
    inputPricePer1k: 0.00125,
    outputPricePer1k: 0.005,
    contextWindow: 2000000,
    isFlagship: true,
  },
  {
    provider: 'Google',
    model: 'gemini-1.5-flash',
    displayName: 'Gemini 1.5 Flash',
    inputPricePer1k: 0.000075,
    outputPricePer1k: 0.0003,
    contextWindow: 1000000,
    isPopular: true,
  },
  {
    provider: 'Google',
    model: 'gemini-2.0-flash',
    displayName: 'Gemini 2.0 Flash',
    inputPricePer1k: 0.0001,
    outputPricePer1k: 0.0004,
    contextWindow: 1000000,
    isPopular: true,
  },
  // Mistral Models
  {
    provider: 'Mistral',
    model: 'mistral-large',
    displayName: 'Mistral Large',
    inputPricePer1k: 0.002,
    outputPricePer1k: 0.006,
    contextWindow: 128000,
    isFlagship: true,
  },
  {
    provider: 'Mistral',
    model: 'mistral-small',
    displayName: 'Mistral Small',
    inputPricePer1k: 0.0002,
    outputPricePer1k: 0.0006,
    contextWindow: 32000,
    isPopular: true,
  },
  {
    provider: 'Mistral',
    model: 'mistral-7b',
    displayName: 'Mistral 7B',
    inputPricePer1k: 0.00025,
    outputPricePer1k: 0.00025,
    contextWindow: 32000,
  },
  {
    provider: 'Mistral',
    model: 'codestral',
    displayName: 'Codestral',
    inputPricePer1k: 0.0003,
    outputPricePer1k: 0.0009,
    contextWindow: 32000,
  },
  // Anthropic Models (for future extensibility)
  {
    provider: 'Anthropic',
    model: 'claude-3-5-sonnet',
    displayName: 'Claude 3.5 Sonnet',
    inputPricePer1k: 0.003,
    outputPricePer1k: 0.015,
    contextWindow: 200000,
    isFlagship: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-3-haiku',
    displayName: 'Claude 3 Haiku',
    inputPricePer1k: 0.00025,
    outputPricePer1k: 0.00125,
    contextWindow: 200000,
    isPopular: true,
  },
  {
    provider: 'Anthropic',
    model: 'claude-3-opus',
    displayName: 'Claude 3 Opus',
    inputPricePer1k: 0.015,
    outputPricePer1k: 0.075,
    contextWindow: 200000,
  },
]

export const providers = [...new Set(modelPrices.map(m => m.provider))]
